services:
  app:
    image: datalith:media
    container_name: datalith
    build:
      context: .
      target: media
    restart: unless-stopped
    init: true
    stop_grace_period: 1m
    environment:
      DATALITH_MAX_FILE_SIZE: 2 GiB
      DATALITH_WORKERS: 1
      DATALITH_TASK_RETENTION_SECONDS: 604800
    volumes:
      - ~/docker/datalith/db:/app/data
    ports:
      - "127.0.0.1:1111:1111"
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "3"
