[package]
name = "datalith"
version = "0.2.0"
authors = ["Magic Len <len@magiclen.org>"]
edition = "2024"
rust-version = "1.94"
repository = "https://github.com/magiclen/datalith"
homepage = "https://magiclen.org/datalith"
keywords = ["datalith", "sqlite", "storage", "file", "oss"]
categories = ["filesystem", "database"]
description = "A file management system powered by SQLite for metadata storage and the file system for file storage."
license = "MIT"
include = ["src/**/*", "Cargo.toml", "README.md", "LICENSE"]

[dependencies]
datalith-core = { version = "0.2", path = "../datalith-core", default-features = false, features = ["openapi"] }

clap = { version = "4", features = ["derive", "env"] }
terminal_size = "0.4"

anyhow = "1"

tokio = { version = "1", features = ["fs", "io-util", "macros", "rt-multi-thread", "sync", "time"] }

serde_json = "1"
serde = { version = "1", features = ["derive"] }
utoipa = { version = "6", features = ["chrono", "uuid", "rocket_extras"] }
utoipa-swagger-ui = { version = "10", features = ["rocket", "vendored", "minified"] }
url-escape = "0.1"
byte-unit = "5"

rocket = { version = "0.5", features = ["uuid", "json"]}
rocket-multipart-form-data = "0.11"


[features]
default = ["magic", "image-convert", "av-convert"]
magic = ["datalith-core/magic"]
image-convert = ["datalith-core/image-convert"]
av-convert = ["datalith-core/av-convert"]
[dev-dependencies]
tempfile = "3"
