name: CI-version

on:
  push:
    tags:
      - "v*"

env:
  CARGO_TERM_COLOR: always

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        toolchain: [stable, nightly]
        features: ["", "--no-default-features"]
    name: Test ${{ matrix.toolchain }} (${{ matrix.features }})
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
      - run: bash .github/scripts/install-imagemagick.sh
        if: matrix.features != '--no-default-features'
      - uses: actions-rust-lang/setup-rust-toolchain@v2.0.0
        with:
          toolchain: ${{ matrix.toolchain }}
      - run: cargo test --locked --workspace --release ${{ matrix.features }}
      - run: cargo doc --locked --workspace --release ${{ matrix.features }}

  MSRV:
    strategy:
      fail-fast: false
      matrix:
        toolchain: ["1.94.1"]
        features: ["", "--no-default-features"]
    name: Test MSRV ${{ matrix.toolchain }} (${{ matrix.features }})
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
      - run: bash .github/scripts/install-imagemagick.sh
        if: matrix.features != '--no-default-features'
      - uses: actions-rust-lang/setup-rust-toolchain@v2.0.0
        with:
          toolchain: ${{ matrix.toolchain }}
      - run: cargo test --locked --workspace --release --lib --bins ${{ matrix.features }}
