name: CI

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: actions-rust-lang/setup-rust-toolchain@v2.0.0
        with:
          toolchain: nightly
          components: rustfmt
      - run: cargo +nightly fmt --all -- --check

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
      - run: bash .github/scripts/install-imagemagick.sh
      - uses: actions-rust-lang/setup-rust-toolchain@v2.0.0
        with:
          components: clippy
      - run: cargo clippy --locked --workspace --all-targets --all-features -- -D warnings

  tests:
    strategy:
      fail-fast: false
      matrix:
        toolchain: [stable, nightly]
        features: ["", "--no-default-features"]
    name: Test ${{ matrix.toolchain }} (${{ matrix.features }})
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
      - run: bash .github/scripts/install-imagemagick.sh
        if: matrix.features != '--no-default-features'
      - uses: actions-rust-lang/setup-rust-toolchain@v2.0.0
        with:
          toolchain: ${{ matrix.toolchain }}
      - run: cargo test --locked --workspace ${{ matrix.features }}
      - run: cargo doc --locked --workspace ${{ matrix.features }}

  MSRV:
    strategy:
      fail-fast: false
      matrix:
        toolchain: ["1.94.1"]
        features: ["", "--no-default-features"]
    name: Test MSRV ${{ matrix.toolchain }} (${{ matrix.features }})
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
      - run: bash .github/scripts/install-imagemagick.sh
        if: matrix.features != '--no-default-features'
      - uses: actions-rust-lang/setup-rust-toolchain@v2.0.0
        with:
          toolchain: ${{ matrix.toolchain }}
      - run: cargo test --locked --workspace --lib --bins ${{ matrix.features }}
